"""Enrichment task tracker for AI-driven prospecting follow-ups."""
from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlalchemy import Integer, String, Text, DateTime, ForeignKey, Index
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.db.database import Base


class EnrichmentTask(Base):
    """Generated by the Lead Planner & Scorer when an account/person needs further enrichment.

    `task_type` examples: firmographic_base, hiring_scrape, funding_lookup,
    techstack_lookup, contact_discovery.
    `target_type` is "account" (companies.id) or "person" (people.id).
    `priority` 1 (lowest) – 5 (highest).
    """

    __tablename__ = "enrichment_tasks"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    target_type: Mapped[str] = mapped_column(String(20), nullable=False)
    target_id: Mapped[int] = mapped_column(Integer, nullable=False)
    task_type: Mapped[str] = mapped_column(String(50), nullable=False)
    priority: Mapped[int] = mapped_column(Integer, nullable=False, default=3, server_default="3")
    reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending", server_default="pending")
    created_by_icp_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("icps.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    __table_args__ = (
        Index("ix_enrichment_tasks_target", "target_type", "target_id"),
        Index("ix_enrichment_tasks_status", "status"),
        Index("ix_enrichment_tasks_priority", "priority"),
    )
