"""Enrichment tasks API — list / update / delete tasks generated by the Lead Planner."""
from __future__ import annotations

import math
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy import select, func as sa_func
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.database import get_db
from app.models.enrichment_task import EnrichmentTask

router = APIRouter()


class EnrichmentTaskOut(BaseModel):
    model_config = {"from_attributes": True}

    id: int
    target_type: str
    target_id: int
    task_type: str
    priority: int
    reason: Optional[str]
    status: str
    created_by_icp_id: Optional[int]
    created_at: datetime
    completed_at: Optional[datetime]
    notes: Optional[str]
    # Optional joined display fields
    target_name: Optional[str] = None


class EnrichmentTaskListResponse(BaseModel):
    tasks: list[EnrichmentTaskOut]
    total: int
    page: int
    page_size: int
    total_pages: int


class EnrichmentTaskUpdate(BaseModel):
    status: Optional[str] = None  # 'pending' | 'completed' | 'failed' | 'cancelled'
    notes: Optional[str] = None
    priority: Optional[int] = None


@router.get("", response_model=EnrichmentTaskListResponse)
async def list_enrichment_tasks(
    target_type: Optional[str] = Query(None),
    target_id: Optional[int] = Query(None),
    task_type: Optional[str] = Query(None),
    status: Optional[str] = Query(None),
    priority_min: Optional[int] = Query(None),
    icp_id: Optional[int] = Query(None),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=1, le=200),
    db: AsyncSession = Depends(get_db),
):
    q = select(EnrichmentTask).order_by(
        EnrichmentTask.priority.desc(), EnrichmentTask.created_at.desc()
    )
    if target_type:
        q = q.where(EnrichmentTask.target_type == target_type)
    if target_id is not None:
        q = q.where(EnrichmentTask.target_id == target_id)
    if task_type:
        q = q.where(EnrichmentTask.task_type == task_type)
    if status:
        q = q.where(EnrichmentTask.status == status)
    if priority_min is not None:
        q = q.where(EnrichmentTask.priority >= priority_min)
    if icp_id is not None:
        q = q.where(EnrichmentTask.created_by_icp_id == icp_id)

    total = (await db.execute(select(sa_func.count()).select_from(q.subquery()))).scalar() or 0
    rows = (
        await db.execute(q.offset((page - 1) * page_size).limit(page_size))
    ).scalars().all()

    # Best-effort: enrich with target name (company or person)
    out: list[EnrichmentTaskOut] = []
    if rows:
        from app.models.company import Company
        from app.models.person import Person
        company_ids = [t.target_id for t in rows if t.target_type == "account"]
        person_ids = [t.target_id for t in rows if t.target_type == "person"]
        names: dict[tuple[str, int], str] = {}
        if company_ids:
            r = await db.execute(select(Company.id, Company.name).where(Company.id.in_(company_ids)))
            for cid, cname in r.all():
                names[("account", cid)] = cname
        if person_ids:
            r = await db.execute(
                select(Person.id, Person.first_name, Person.last_name).where(Person.id.in_(person_ids))
            )
            for pid, fn, ln in r.all():
                names[("person", pid)] = f"{fn} {ln}".strip()

        for t in rows:
            o = EnrichmentTaskOut.model_validate(t)
            o.target_name = names.get((t.target_type, t.target_id))
            out.append(o)

    return EnrichmentTaskListResponse(
        tasks=out,
        total=total,
        page=page,
        page_size=page_size,
        total_pages=math.ceil(total / page_size) if total else 1,
    )


@router.patch("/{task_id}", response_model=EnrichmentTaskOut)
async def update_enrichment_task(
    task_id: int, data: EnrichmentTaskUpdate, db: AsyncSession = Depends(get_db)
):
    t = await db.get(EnrichmentTask, task_id)
    if not t:
        raise HTTPException(404, "Task not found")
    if data.status is not None:
        t.status = data.status
        if data.status in ("completed", "cancelled", "failed") and t.completed_at is None:
            t.completed_at = datetime.now(timezone.utc)
    if data.notes is not None:
        t.notes = data.notes
    if data.priority is not None:
        if data.priority < 1 or data.priority > 5:
            raise HTTPException(400, "priority must be between 1 and 5")
        t.priority = data.priority
    await db.flush()
    await db.refresh(t)
    return EnrichmentTaskOut.model_validate(t)


@router.delete("/{task_id}", status_code=204)
async def delete_enrichment_task(task_id: int, db: AsyncSession = Depends(get_db)):
    t = await db.get(EnrichmentTask, task_id)
    if not t:
        raise HTTPException(404, "Task not found")
    await db.delete(t)
